pedidos/urls.py
from django.urls import path

from . import views

urlpatterns = [
  path('', views.index, name='index'),
  path('cardapio/', views.cardapio, name='cardapio'),
  path('mesas/', views.mesas, name='mesas'),
  path('lista_pedidos/', views.lista_pedidos, name='lista_pedidos'),
  path('form_pedido/', views.form_pedido, name='form_pedido'),
  path('atualizar_pedido/<int:pk>/', views.atualizar_pedido, name='atualizar_pedido'),
  path('deletar_pedido/<int:pk>/', views.deletar_pedido, name='deletar_pedido'),
  path('financeiro/', views.financeiro, name='financeiro'),
  path('pagamento/<int:pk>/', views.pagamento, name='pagamento'),
  path('atualizar_status/', views.atualizar_status, name='atualizar_status')
]

uaifood/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('authentication.urls')),
    path('', include('pedidos.urls')),
    path('admin/', admin.site.urls),
]

pedidos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.functions import Coalesce
from django.db.models import Sum, Value, F
from decimal import Decimal

STATUS_CHOICES = (
      (0, "Disponível"),
      (1, "Indisponível")
    )

STATUS_PEDIDO_CHOICES = (
      (1, "EM ANDAMENTO"),
      (2, "PRONTO")

    )

MESAS_CHOICES = (
    (1, "MESA 01"),
    (2, "MESA 02"),
    (3, "MESA 03"),
    (4, "MESA 04"),
    (5, "MESA 05")
  )

FORMA_PAGTO_CHOICES = (
      (1, "DINHEIRO"),
      (2, "CARTÃO DÉBITO"),
      (3, "CARTÃO CRÉDITO"),
      (4, "PIX")
    )

STATUS_CAIXAS_CHOICES = (
      (1, "PENDENTE"),
      (2, "PAGO")
    )

class Categoria(models.Model):
  nome = models.CharField(max_length=100)
  descricao = models.CharField(max_length=100)

  def __str__(self):
    return self.nome

class Prato(models.Model):
  nome = models.CharField(max_length=100)
  categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
  descricao = models.CharField(max_length=100)
  status = models.BooleanField(choices=STATUS_CHOICES)
  valor = models.DecimalField(max_digits=5, decimal_places=2)
  criado = models.DateTimeField(auto_now_add=True)
  atualizado = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.nome

class Pedido(models.Model):
  usuario = models.ForeignKey(User, related_name='usuario_pedido', on_delete=models.CASCADE)
  data = models.DateTimeField(auto_now_add=True)
  mesa = models.IntegerField(choices=MESAS_CHOICES)
  status = models.IntegerField(choices=STATUS_PEDIDO_CHOICES)

  @property
  def get_total_pedido(self):
    return self.itens_pedido.aggregate(total_pedido=Coalesce(Sum(F('valor')*F('quantidade')), Decimal(0)))['total_pedido']

  def __str__(self):
    return ' '.join(['#Pedido', str(self.id), 'Mesa',str(self.mesa)])
  
class Estoque(models.Model):
    quantidade = models.IntegerField()
    status = models.BooleanField(choices=STATUS_CHOICES)
    prato = models.ForeignKey(Prato, on_delete=models.CASCADE)
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)
    validade = models.DateField()

class ItemPedido(models.Model):
  prato = models.ForeignKey(Prato, on_delete=models.CASCADE)
  pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, related_name="itens_pedido")
  quantidade = models.IntegerField()
  valor = models.DecimalField(max_digits=5, decimal_places=2)
  
  def save(self):
        self.valor = Prato.objects.only('valor').get(pk=self.prato.id).valor
        super(ItemPedido, self).save()

  def __str__(self):
    return '#Pedido '+str(self.pedido.id)
  

class Caixa(models.Model):
  pedido = models.OneToOneField(Pedido, on_delete=models.CASCADE, related_name="caixa_pedido")
  valor = models.DecimalField(max_digits=5, decimal_places=2)
  status = models.BooleanField()
  pagamento = models.IntegerField(choices=FORMA_PAGTO_CHOICES)

pedidos/forms.py
from django import forms
from pedidos.models import MESAS_CHOICES, STATUS_PEDIDO_CHOICES, FORMA_PAGTO_CHOICES, ItemPedido, Pedido, Prato, Caixa
from django.forms.models import inlineformset_factory

class PedidoForm(forms.ModelForm):
  mesa = forms.ChoiceField(label='Mesa', choices=MESAS_CHOICES, widget=forms.Select(attrs={'class': "form-control"}))
  status = forms.ChoiceField(label='Status', choices=STATUS_PEDIDO_CHOICES, widget=forms.Select(attrs={'class': "form-control"}))
  
  class Meta:
    model = Pedido
    fields = ['mesa', 'status']
    
class ItemPedidoForm(forms.ModelForm):
  prato = forms.ModelChoiceField(label='Prato', queryset=Prato.objects.all(), widget=forms.Select(attrs={'class': "form-control"}))
  quantidade = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
  
  class Meta:
    model = ItemPedido
    fields = ['prato', 'quantidade']
    
    
FormSetItemPedido = inlineformset_factory(
  Pedido, ItemPedido, form=ItemPedidoForm, extra=0, can_delete=True,
  min_num=0, validate_min=True
) 

class PagamentoForm(forms.ModelForm):
  pagamento = forms.ChoiceField(label='Forma de Pagamento', choices=FORMA_PAGTO_CHOICES, widget=forms.Select(attrs={'class': "form-control"}))

  class Meta:
    model = Caixa
    fields = ['pagamento']

pedidos/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from pedidos.models import STATUS_PEDIDO_CHOICES, MESAS_CHOICES, Pedido, Prato, Caixa
from pedidos.forms import PedidoForm, FormSetItemPedido, PagamentoForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.db.models import Sum

@login_required
def index(request):
  pedidos = Pedido.objects.all().order_by('-id')
  paginator = Paginator(pedidos, 6)
  page = request.GET.get('page')
  pedidos_por_pagina = paginator.get_page(page)
  
  data = {
    'pedidos': pedidos_por_pagina
  }
  return render(request,'home/index.html', data)

@login_required
def cardapio(request):
  pratos = Prato.objects.all().order_by('-id')
  paginator = Paginator(pratos, 6)
  page = request.GET.get('page')
  pratos_por_pagina = paginator.get_page(page)
  
  data = {
    'pratos': pratos_por_pagina
  }
  return render(request,'home/cardapio.html', data)


@login_required
def lista_pedidos(request):

  pratos = Prato.objects.all()
  data = {
    'pratos': pratos
  }
  return render(request,'home/lista_pedidos.html', data)


@login_required
def form_pedido(request):
    if request.method == 'POST':
        form = PedidoForm(request.POST)

        if form.is_valid():
            pedido = form.save(commit=False)
            pedido.usuario = request.user
            pedido.save()
            return redirect('atualizar_pedido', pk=pedido.id)
        else:
            return render(request, 'home/formPedido.html', {'form': form })
    else:
        form = PedidoForm()

    return render(request, 'home/formPedido.html', {'form': form })
  
  
@login_required
def atualizar_pedido(request, pk):
    pedido = get_object_or_404(Pedido, id=pk)
    form = PedidoForm(request.POST or None, instance=pedido)
    form_set_items = FormSetItemPedido(request.POST or None, instance=pedido)
    data = {'form': form, 'pedido': pedido, 'form_items': form_set_items}
    
    if request.method == 'POST':
  
        if form.is_valid() and form_set_items.is_valid():
            form.save()
            form_set_items.save()
            return redirect('atualizar_pedido',  pk=pedido.id)
        else:
            return render(request, 'home/formPedido.html', data)

    return render(request, 'home/formPedido.html', data)


@login_required
def deletar_pedido(request, pk):
    pedido = get_object_or_404(Pedido, id=pk,)

    if request.method == "POST":
        pedido.delete()
        return HttpResponseRedirect("/")


@login_required
def mesas(request):

  mesas = MESAS_CHOICES
  data = {
    'mesas': mesas
  }
  return render(request,'home/mesas.html', data)


@login_required
def financeiro(request):
  
  caixas = Caixa.objects.all()
  total = Caixa.objects.all().aggregate(total_pagamentos=Sum('valor'))
  data = {
    'caixas': caixas,
    'total': total
  }
  return render(request,'home/financeiro.html', data)


@login_required
def pagamento(request, pk):
    pedido = get_object_or_404(Pedido, id=pk)
    if request.method == 'POST':
        form = PagamentoForm(request.POST)
        existe = Caixa.objects.filter(pedido=pedido).exists()
        valor_zerado = pedido.itens_pedido.count()
        if existe is False and valor_zerado>0:
          if form.is_valid():
              pagto = form.save(commit=False)
              pagto.valor = pedido.get_total_pedido
              pagto.pedido = pedido
              pagto.status=True
              pagto.save()
              return redirect('financeiro')
          else:
              return render(request, 'home/form_pagamento.html', {'form': form, 'pedido': pedido})
        else:
          if existe:
            messages.error(request, "Pedido ja em Caixa!")
          if valor_zerado == 0:
            messages.error(request, "Pedido sem valor!")
          return render(request, 'home/form_pagamento.html', {'form': form, 'pedido': pedido})
    else:
        form = PagamentoForm()

    return render(request, 'home/form_pagamento.html', {'form': form, 'pedido': pedido})
  
  
@login_required
def atualizar_status(request):
  status = STATUS_PEDIDO_CHOICES
  data = {
    'status': status
  }
  return render(request,'home/modal_fecha_pedido.html', data)

templates/home/cardapio.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Cardápio {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<!-- Header -->
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row">

    <div class="col-xl-8">
      <div class="card">
        <div class="card-header border-0">
          <div class="row align-items-center">
            <div class="col">
              <h3 class="mb-0">Cardápio</h3>
            </div>
          </div>
        </div>
        <div class="table-responsive">
          <!-- Projects table -->
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">NOME</th>
                <th scope="col">CATEGORIA</th>
                <th scope="col">VALOR</th>
                <th scope="col">STATUS</th>
              </tr>
            </thead>
            <tbody>
              {% for prato in pratos %}
                  <tr>
                    <th scope="row">
                      {{ prato.id }}
                    </th>
                    <td>
                      {{ prato.nome }}
                    </td>
                    <td>
                      {{ prato.categoria }}
                    </td>
                    <td>
                      {{ prato.valor }}
                    </td>
                    <td>
                      {{ prato.get_status_display }}
                    </td>
                  </tr>
              {%endfor%}
            </tbody>
          </table>
        </div>
      </div>

         <!-- ##### Pagination ##### -->
<section class="top-catagory-area section-padding-20-0">
  <div class="container">
      {% if pratos.has_other_pages %}
      <ul class="pagination">
          {% if pratos.has_previous %}
          <li class="page-item">
              <a href="?page={{ pedidos.previous_page_number }}" class="page-link">&laquo;</a>
          </li>
          {% else %}
          <li class="page-item disabled">
              <a class="page-link">&laquo;</a>
          </li>
          {% endif %}
          {% for pagina in pratos.paginator.page_range %}
          {% if pratos.number == pagina %}
          <li class="page-item active">
              <a class="page-link">{{ pagina }}</a>
          </li>
          {% else %}
          <li class="page-item">
              <a href="?page={{pagina}}" class="page-link">{{pagina}}</a>
          </li>
          {% endif %}
          {% endfor %}
          {% if pagina.has_next %}
          <li class="page-item">
              <a href="?page={{ pagina.next_page_number }}" class="page-link">&raquo;</a>
          </li>
          {% else %}
          <li class="page-item disabled">
              <a class="page-link">&raquo;</a>
          </li>
          {% endif %}
      </ul>
      {% endif %}
  </div>
</section>
<!-- ##### Pagination End ##### -->

    </div>
    <div class="col-xl-4">
    </div>
  </div>

   

  {% include "includes/footer.html" %}

</div>

{% endblock content %}

templates/home/financeiro.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Cardápio {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<!-- Header -->
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row">

    <div class="col-xl-10">
      <div class="card">
        <div class="card-header border-0">
          <div class="row align-items-center">
            <div class="col">
              <h3 class="mb-0">Financeiro</h3>
            </div>
          </div>
        </div>
        <div class="table-responsive">
          <!-- Projects table -->
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">PEDIDO</th>
                <th scope="col">VALOR</th>
              </tr>
            </thead>
            <tbody>
              {% for caixa in caixas %}
                  <tr>
                    <th scope="row">
                      {{ caixa.id }}
                    </th>
                    <td>
                      {{ caixa.pedido.id }}
                    </td>
                    <td>
                      {{ caixa.valor }}
                    </td>
                  </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
   
    <div class="col-xl-5" style='margin-left: 445px;' >
      <div class="card">
        <div class="card-header border-0">
          <div class="row align-items-center">
            <div class="col">
              <h3 class="mb-0">Total Geral</h3>
            </div>
          </div>
        </div>
        <div class="table-responsive">
         
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col">VALOR</th>
                <th scope="col"></th>
               
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  {{total.total_pagamentos}}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    
    </div>
  </div>

  {% include "includes/footer.html" %}

</div>

{% endblock content %}

templates/home/formPedido.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Cardápio {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<!-- Header -->
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col-xl-8 order-xl-1">
      <div class="card">
        <div class="card-header">
          <div class="row align-items-center">
            <div class="col-12">
              <h3 class="mb-0">Lançar Pedido </h3>
              <a href="{% url 'index' %}" class="btn btn-sm  btn-primary" style="font-size: 15px; padding-left: 20px; padding-right: 20px; float: right; "> Voltar </a>
            </div>
            
          </div>
        </div>
        <div class="card-body">
          <form method="POST" >
            {% csrf_token %}
            <h6 class="heading-small text-muted mb-4">Informações do pedido</h6>
            {% for field in form %}
            <p>{{ field.label_tag }} {{ field }} </p>
            {% if form.errors %}
            {% for error in field.errors %}
            <p class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </p>
            {% endfor %}
            {% endif %}
            {% if field.help_text %}
            <p class="form-text">{{ field.help_text|safe }}</p>
            {% endif %}
            {% endfor %}

            {{ form_items.management_form }}
            <div id="form_set">
                {% for form_item in form_items.forms %}
                    <table class='no_error'>
                        {{ form_item.as_table }}
                    </table>
                {% endfor %}
            </div>
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
              {% if pedido %}
                <input type="button" class="btn btn-sm  btn-primary" value="Adicionar" id="add_more" style="font-size: 17px; margin-right: 20px; background-color: #0d2295; background-color: #0d2295;">
              {% endif %}

              <div id="empty_form" style="display:none">
                  <table class='no_error'>
                      {{ form_items.empty_form.as_table }}
                  </table>
              </div>

              <button type="submit" class="btn btn-sm  btn-primary" style="font-size: 17px; padding-left: 20px; padding-right: 20px; "> 
                {% if pedido%} Atualizar Pedido {% else %} Criar Pedido {% endif %}
              </button>

              </form>
            {% if pedido %}
              <form action="{% url 'deletar_pedido' pk=pedido.pk %}" method="POST" onsubmit="return confirm ('Deseja deletar esse pedido?')">
                {% csrf_token %}
                <button type="submit" class="btn btn-sm  btn-primary" style="font-size: 17px; padding-left: 20px; padding-right: 20px; background-color: red; border-color: red; margin-left: 160px;"> Deletar Pedido </button>
              </form>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    $('#add_more').click(function() {
        var form_idx = $('#id_itens_pedido-TOTAL_FORMS').val();
        $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
        $('#id_itens_pedido-TOTAL_FORMS').val(parseInt(form_idx) + 1);
    });
  </script>

  {% include "includes/footer.html" %}

</div>

{% endblock content %}

templates/home/form_pagamento.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Cardápio {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<!-- Header -->
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col-xl-8 order-xl-1">
      <div class="card">
        <div class="card-header">
          <div class="row align-items-center">
            <div class="col-12">
              <h3 class="mb-0">Forma de Pagamento </h3>
              <a href="{% url 'index' %}" class="btn btn-sm  btn-primary" style="font-size: 15px; padding-left: 20px; padding-right: 20px; float: right; "> Voltar </a>
            </div>
            
          </div>
        </div>
        <div class="card-body">
          <h6 class="heading-small text-muted mb-4">Informações do pedido</h6>
          <h6 class="heading-small text-muted mb-2">Pedido</h6>
          {{ pedido.id }}
          <h6 class="heading-small text-muted mb-2">Valor</h6>
          {{ pedido.get_total_pedido }}
          <form method="POST" >
            {% csrf_token %}
            {% for field in form %}
            <p>
              <h6 class="heading-small text-muted mb-2">{{ field.label }}</h6>
              {{ field }} 
            </p>
            {% if form.errors %}
            {% for error in field.errors %}
            <p class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </p>
            {% endfor %}
            {% endif %}
            {% if field.help_text %}
            <p class="form-text">{{ field.help_text|safe }}</p>
            {% endif %}
            {% endfor %}

            <div class="btn-group btn-group-toggle" data-toggle="buttons">
              
              <button type="submit" class="btn btn-sm  btn-primary" style="font-size: 17px; padding-left: 20px; padding-right: 20px; "> 
                Pagar pedido
              </button>

          </form>
           
          </div>
        </div>
      </div>
    </div>
  </div>

  {% include "includes/footer.html" %}

</div>

{% endblock content %}

templates/home/index.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Dashboard {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Header -->
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Page content -->
    <div class="container-fluid mt--6">
      <div class="row">

       {% include 'home/pedidos.html' %}
       
        <!-- aqui vai um card -->
        <div class="col-xl-3 col-md-6">
          <div class="card card-stats">
            <!-- Card body -->
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <h5 class="card-title text-uppercase text-muted mb-0">Mesa mais atendida</h5>
                  <span class="h1 font-weight-bold mb-0" style="font-size: 50px;">02</span><br>
                  <span class="h2 font-weight-bold" style="">2ª mesa</span><br>
                  <span class="h2 font-weight-bold mb-0" style="font-size: 30px;">01</span>
                </div>
                
              </div>
            </div>
          </div>
        </div>

      </div>

      {% include "includes/footer.html" %}

    </div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="{% static 'assets/vendor/chart.js/dist/Chart.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/dist/Chart.extension.js' %}"></script>

{% endblock javascripts %}

templates/home/lista_pedidos.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Cardápio {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<!-- Header -->
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row">

    <div class="col-xl-8">
      <div class="card">
        <div class="card-header border-0">
          <div class="row align-items-center">
            <div class="col">
              <h3>Lançar pedido</h3>
              
            </div>
            <a href="{% url 'form_pedido' %}" class="btn btn-sm  btn-primary" style="font-size: 20px; padding-left: 20px; padding-right: 20px; "> + </a>
          </div>
        </div>
        <div class="table-responsive">
          <!-- Projects table -->
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">NOME</th>
                <th scope="col">CATEGORIA</th>
                <th scope="col">VALOR</th>
                <th scope="col">STATUS</th>
              </tr>
            </thead>
            <tbody>
              {% for prato in pratos %}
                  <tr>
                    <th scope="row">
                      {{ prato.id }}
                    </th>
                    <td>
                      {{ prato.nome }}
                    </td>
                    <td>
                      {{ prato.categoria }}
                    </td>
                    <td>
                      {{ prato.valor }}
                    </td>
                    <td>
                      {{ prato.get_status_display }}
                    </td>
                  </tr>
              {%endfor%}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  {% include "includes/footer.html" %}

</div>

{% endblock content %}

templates/home/mesas.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block title %} Cardápio {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<!-- Header -->
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row">

    <div class="col-xl-8">
      <div class="card">
        <div class="card-header border-0">
          <div class="row align-items-center">
            <div class="col">
              <h3 class="mb-0">Mesas</h3>
            </div>
          </div>
        </div>
        <div class="table-responsive">
          <!-- Projects table -->
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col">Mesas</th>
              </tr>
            </thead>
            <tbody>
              {% for pedido in pedidos %}
                  <tr>
                    <th scope="row">
                      {{ pedido.get_mesa_display }}
                    </th>
                    <td>
                      
                    </td>
                  </tr>
              {%endfor%}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  {% include "includes/footer.html" %}

</div>

{% endblock content %}

templates/home/pedidos.html
<div class="col-xl-8">
  <div class="card">
    <div class="card-header border-0">
      <div class="row align-items-center">
        <div class="col">
          <h3 class="mb-0">Pedidos</h3>
        </div>
        <a href="{% url 'form_pedido' %}" class="btn btn-sm  btn-primary" style="font-size: 20px; padding-left: 20px; padding-right: 20px; "> + </a>
      </div>
    </div>
    <div class="table-responsive">
      <!-- Projects table -->
      <table class="table align-items-center table-flush">
        <thead class="thead-light">
          <tr>
            <th scope="col">ID</th>
            <th scope="col">RESUMO</th>
            <th scope="col">MESA</th>
            <th scope="col">VALOR</th>
            <th scope="col">STATUS</th>
            <th scope="col">PAGAMENTO</th>
          </tr>
        </thead>
        <tbody>
          {% for pedido in pedidos %}
              <tr>
                <th scope="row">
                  <a href="{% url 'atualizar_pedido' pedido.id %}">#{{ pedido.id }}</a>
                </th>
                <td>
                  {{ pedido.itens_pedido.count }} Itens
                </td>
                <td>
                  {{ pedido.get_mesa_display }}
                </td>
                <td>
                  {{ pedido.get_total_pedido }}
                </td>
                <td>
                    <a href="" id="muda_status">
                      {{ pedido.get_status_display }}
                    </a>
                </td>
                <td>
                    {% if pedido.caixa_pedido %}
                      <p style="color:#2dce89; font-weight: 700; ">Pago</p>
                    {% else %}
                      <a href=" {% url 'pagamento' pedido.id %} " class="btn btn-success">Pagar</a>
                    {% endif %}
                </td>
              </tr>
          {%endfor%}
        </tbody>
      </table>
    </div>
  </div>
    <!-- ##### Pagination ##### -->
<section class="top-catagory-area section-padding-20-0">
  <div class="container">
      {% if pedidos.has_other_pages %}
      <ul class="pagination">
          {% if pedidos.has_previous %}
          <li class="page-item">
              <a href="?page={{ pedidos.previous_page_number }}" class="page-link">&laquo;</a>
          </li>
          {% else %}
          <li class="page-item disabled">
              <a class="page-link">&laquo;</a>
          </li>
          {% endif %}
          {% for pagina in pedidos.paginator.page_range %}
          {% if pedidos.number == pagina %}
          <li class="page-item active">
              <a class="page-link">{{ pagina }}</a>
          </li>
          {% else %}
          <li class="page-item">
              <a href="?page={{pagina}}" class="page-link">{{pagina}}</a>
          </li>
          {% endif %}
          {% endfor %}
          {% if pagina.has_next %}
          <li class="page-item">
              <a href="?page={{ pagina.next_page_number }}" class="page-link">&raquo;</a>
          </li>
          {% else %}
          <li class="page-item disabled">
              <a class="page-link">&raquo;</a>
          </li>
          {% endif %}
      </ul>
      {% endif %}
  </div>
</section>

<script>
  $('#muda_status').click(function() {
    
    {{ pedido.get_status_display }} = "OI AMOR"
  });
</script>

</div>